### ISSUE TITLE
"What's New" on Beta page points to dead link

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#13]
The "What's New" link on the Beta page points to [this non-existent page](https://www.thunderbird.net/en-US/thunderbird/58.0beta/releasenotes/) - we should see if we can fix this. Can we autogenerate those release notes? Where do they come from?

**Comment by wsmwk** [comment]
I'm not sure https://www.thunderbird.net/en-US/channel/ is considered "live". 

OTOH, the "What's New" link from https://www.mozilla.org/en-US/thunderbird/channel/ is good.

**Comment by Sancus** [comment]
Fixed this yesterday, but yes, while it is more or less usable, thunderbird.net is not the canonical url as long as mozilla.org exists. I didn't realize you were gonna blog post it :) I have to manually sync the release notes, and they're here: https://github.com/thundernest/thunderbird-notes

When we switch over in the new year, jorg will do release notes in that repo instead of the mozilla system, so thunderbird.net will be the canonical url.
