### ISSUE TITLE
Fetch blog posts via REST API

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderbird-website#133]
I'm opening this issue as a personal reminder.
I need to automatically fetch the latest posts from our blog using the WordPress REST API.
The 3 most recent blog posts are shown in the new home page.

**Comment by Sancus** [comment]
I was planning to do this myself, but either way, I think it should be done when the page is generated and then just cached in the final product. Not with JS on page load, mainly for security reasons. I can run a build every 24h to pick up new blog posts.

Also, the whole blog post section of the page should probably be en-US only? There isn't really going to be a practical way to translate it.

**Comment by Alecaddd** [comment]
Oh nice, yes, if you can take care of it it would be amazing.
I agree with the direction and not fetching the posts at every page load.

**Comment by Sancus** [comment]
This is fixed now. I used the summary that wordpress puts in the feeds, which includes a "continue reading" link at the end. Other than that, there aren't any links, but the [link data is there](https://github.com/thundernest/thunderbird-website/blob/redesign/helper.py#L366) if you want to use it.

Also, it's probably possible to change the template to a 3 iteration loop to avoid duplicating the HTML for each post, but it would require changing the css classes so that they can be the same on each article, and I didn't really want to mess around with that. It's not a big deal either way since there's only 3 posts.

I made the post summaries themselves, since they'll always be in English, only appear on "en-" pages. However, the static text and big button that links to the blog can be translated, so it [stays in other languages](https://www-new.thunderbird.net/fr/).
