### ISSUE TITLE
hu locale links to en-US instead of hu

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#145]
1. https://www-new.thunderbird.net/hu/
2. Click [Nyelvek és operációs rendszerek](https://www-new.thunderbird.net/en-US/thunderbird/all/) opens https://www-new.thunderbird.net/en-US/thunderbird/all/ when it should open https://www-new.thunderbird.net/hu/thunderbird/all/

* There are other places where `en-US` is shown instead of `hu`. Did you want a list of these places to fix?
* There are also other places where there is no locale when the locale should be added. Did you wan a list of these places too?

Thank you

**Comment by Sancus** [comment]
I guess you can post a list, because you're making a lot of assumptions here. The Systems & Languages page is en-US only traditionally, the localized versions only exist because of a technical detail with the way the page builds. So that isn't a bug.

There are quite a few other pages that are en-US only on the site, not every non-localized link is a bug or unintended.

**Comment by ovari** [comment]
Can you remove all the `en-US` in the links as then the website will:
1. try to open the website in the locale setting; and if unsuccessful
2. try to open the website in the `en-US` setting.

Should https://www-new.thunderbird.net/en-US/thunderbird/all/ be updated to https://www-new.thunderbird.net/thunderbird/all/ ?

What do you think?

Thank you

**Comment by Sancus** [comment]
> Can you remove all the `en-US` in the links as then the website will:
> 
>     1. try to open the website in the locale setting; and if unsuccessful
> 
>     2. try to open the website in the `en-US` setting.
> 

The website does not do that. If you don't use a locale code, you go through the redirects on the Apache server. If you're using one of the urls that is supposed to be localized, the short python script that tries to figure out the right locale from Accept-Language runs. This is quite slow compared to the fixed locale links to static pages, which is why there are no internal links without locale codes. If you're using a url that isn't supposed to be localized, then the Apache server returns a redirect to en-US.

If a page is in the list that is supposed to be en-US only, then the website generates links to en-US. This saves a redirect both for the user and for the server. There is no reason to "try to open the website in the locale setting" first because the website generator knows whether you are supposed to be linked there or not in the first place, and generates the links accordingly.
