### ISSUE TITLE
Beta download on every page, but release button isn't

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#158]
So, because the beta button is in the "pre-footer", it ends up being rendered on many pages, including the Features page, any release notes, etc.

This is a bit odd, especially on the release notes pages, because it means these pages have a beta download button, but no release channel download button. It feels like we're making it harder to find the release download than the beta download.

People have [reported the lack of release download as a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1605524). I think we could go in two directions with this: Somehow add the release download button, or change the way the footer thing works. Or maybe it's fine as-is? It's definitely weird, though.

@Alecaddd @ryanleesipes What do you guys think about this?

**Comment by wsmwk** [comment]
Good summary.   My gut reaction, if it isn't too confusing, is for simplicity just make that spot tri-state and offer all three versions.  

If we don't do that, then I don't know how we offer a download button somewhere else without it being confusing because then we must still make a design choice -  point to a releases page that shows all the releases, point to just a specific release (which means EVERY release page would be a different link), or only point the user to a current release (which I would propose what the footer do).

I've always thought weird but not a big deal that release notes never had a download link.  But we must accomodate users that find the release notes page via search or whatever - they won't always be finding a "download page".

**Comment by Sancus** [comment]
I like the idea of adding the release button to the tabbed footer section, and then just changing which is the "default". So on the front page it could show Beta by default, and then on other pages it could show Release by default, and in general we could use it whenever we want to highlight a particular channel on a particular page.

**Comment by Alecaddd** [comment]
@Sancus I like it, great idea.

**Comment by SteveChessin** [comment]
I was the person who reported that [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1605524). The real problem is that there is no click-path from the release notes page to a page where you can download the release. There used to be, but I never thought to screen-shot the old release notes page format. The new design doesn't have the same information.

**Comment by Sancus** [comment]
> I was the person who reported that [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1605524). The real problem is that there is no click-path from the release notes page to a page where you can download the release.

If you're anywhere on the site(including release notes), you can always click on the Thunderbird icon/text in the top left to get to the front page which has a release download button. "Top left has some kind of home button" is a very common website design pattern, and it's often not explicitly marked anymore.

Also, you can access old versions of our site going back many years via web.archive.org, [for example Release Notes](http://web.archive.org/web/20191116003122/https://www.thunderbird.net/en-US/thunderbird/68.2.2/releasenotes/).

**Comment by SteveChessin** [comment]
> If you're anywhere on the site(including release notes), you can always click on the Thunderbird icon/text in the top left to get to the front page which has a release download button. "Top left has some kind of home button" is a very common website design pattern, and it's often not explicitly marked anymore.

The point is that you (maybe not you personally, but the community) changed the design without thinking that someone used to the old design might not realize that they could get to the front page that way. Also, since the new design has a very obvious Download Beta/Nightly button, one would expect a very obvious Download The Release button as well, and not think to try mousing over all the release notes page looking for a hidden link to a page with a download link.

> Also, you can access old versions of our site going back many years via web.archive.org, [for example Release Notes](http://web.archive.org/web/20191116003122/https://www.thunderbird.net/en-US/thunderbird/68.2.2/releasenotes/).

I appreciate your including that link. As you can see, the old style had that Check/Download/Install/Customize square
![Check:Download:Install:Customize](https://user-images.githubusercontent.com/19721058/71383541-b2e41880-2591-11ea-88f0-c7360b38349b.png) that had the obvious click-path to the page that lets you download the release. The new style has the "Check" information link but not the rest of them. (The new style is also very wasteful of screen space, with too much vertical white space. It requires a lot more scrolling.)

I know that no one likes to be told that their baby is ugly, but the new release notes page is just that.

**Comment by Sancus** [comment]
> I know that no one likes to be told that their baby is ugly, but the new release notes page is just that.

I'm not sure why you're belaboring the point so hard when we've already agreed that there's an issue and planned a potential fix for it. I was only pointing out that stating there's no path to a download button is incorrect. Obviously I know that the page changed. There's going to be issues with any major redesign, that's the nature of the beast.

In any case, I will work on adding a release channel tab to the footer download section after Jan 1st unless Alessandro feels like doing it earlier than that.
