### ISSUE TITLE
add catalina MacOS 10.5 to supported versions on system requirements 

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#178]
Firefox lists it starting at version 70 https://www.mozilla.org/en-US/firefox/70.0/system-requirements/

**Comment by Sancus** [comment]
I assume 68 actually works just fine on Catalina, so I added it there, since most of our versions inherit the detailed system requirements from 68.

If that's not the case, I can make new system requirements for beta 70+, I suppose. Also for future reference, [system requirements are part of the release notes](https://github.com/thundernest/thunderbird-notes).
