### ISSUE TITLE
https://www.thunderbird.net/contact/ is 404 - does not resolve to a language

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#180]
https://www.thunderbird.net/contact/ is 404 - does not resolve to a language

**Comment by Alecaddd** [comment]
Uh, that's weird.
@Sancus, do you know what's up?

**Comment by Sancus** [comment]
This is fixed now.

The redirects are [manually maintained in the Apache config file](https://github.com/thundernest/thundernest-ansible/blob/master/vars/apache.yml#L158) by necessity(you can't put WSGI commands in a .htaccess unfortunately). I forgot to add this one.

I just double checked and all the other pages are covered, so this was the only missing one. It's not that big of a deal since for English only pages you may as well use /en-US/.

The en-US redirects alone could be in an htaccess since they don't use the python l10n script. There's probably some improvements that could be made to automate this setup, but the main reason it is this way is to minimize the number of people who actually hit the Python script. That's probably not needed as long as we use Cloudflare, so I might change this at some point.
