### ISSUE TITLE
There is absolutely no help to download Thunderbird when viewed on mobile browser 📌

### ISSUE THREAD

**Issue by satoshi-n** [thundernest/thunderbird-website#227]
- Unless I request desktop site I cannot see the link to download. Thought I was going insane for half an hour looking for a way to download the file.

**Comment by justdave** [comment]
I've noticed this myself.  Right now it only shows you a download link if you're running on a platform that can run Thunderbird.  But it really ought to (instead of just hiding it) tell you so and give you a link to pick a platform if you want to download it anyway (common use case for this: the computer you want to install it on is air-gapped from the internet and you need to sneakernet the file to it from a different device).

I've gotta screw with download buttons anyway in #158 so I'll try to get this with it.

**Comment by justdave** [comment]
The page is attempting to display download links for all available platfowms any time the operating system of the browser viewing the page isn't one we know about.  Unfortunately, the library we're using to detect the OS of the browser also recognizes Android and iOS, which we don't support, and we don't have download buttons for those OSes as a result. But since we *did* detect the OS and it's not an unknown OS, the alternate download links don't display because it thinks the OS-specific block (which doesn't exist) did.  So the fix is just to add the android and ios tags to the unknown platform blocks so that they display for Android and iOS users.
