### ISSUE TITLE
post-download donation URL points to the wrong donate site

### ISSUE THREAD

**Issue by Pomax** [thundernest/thunderbird-website#254]
It looks like the website is still pointing to the Mozilla Foundation donations website (https://donate.mozila.org), rather than the new Thunderbird-specific donations website (https://give.thunderbird.net). From the donate.mozilla.org logs, it looks like a substantial number of people are clicking through to make a donation (or at the very least consider making a donation) but getting a 503 because the old URL no longer exists.

**Comment by Sancus** [comment]
That's odd, because the old URL redirects to the new one as far as I can tell. But yes, this should be fixed ASAP.

Thanks for the PR. Will push this through to live immediately.

**Comment by Pomax** [comment]
Looks like the unlocalized URL does redirect, but it never got uplifted with locale support so something like https://http://donate.mozilla.org/nl-NL/thunderbird would't work.

**Comment by thomasd8** [comment]
I was downloading Thunderbird a couple of times before this update and it was always showing the Thunderbird donation site correctly.





> It looks like the website is still pointing to the Mozilla Foundation donations website (https://donate.mozila.org),

That's misspelt.

> rather than the new Thunderbird-specific donations website (https://give.thunderbird.net). From the donate.mozilla.org logs, it looks like a substantial number of people are clicking through to make a donation (or at the very least consider making a donation) but getting a 503 because the old URL no longer exists.

Not true. They may end up on the English donation page, but not with 503.

> Looks like the unlocalized URL does redirect, but it never got uplifted with locale support so something like https://donate.mozilla.org/nl-NL/thunderbird would't work

Mozilla uses /nl/ for Nederlands (without -NL), so the above link may not be valid (although it should work as a courtesy).
https://donate.mozilla.org/nl/thunderbird works, but it ends up on the English donation page.

(arguably, neither does https://give.thunderbird.net/nl-NL/thunderbird, but you want those errors to show up in the logs for the TB donate website of course =)

That link won't work because it's wrong:
- /nl/, not /nl-NL/
- trailing /thunderbird is wrong

The correct link is https://give.thunderbird.net/nl/ and that works, and links to the donation page of Nederlands.
However, the donation link from https://www.thunderbird.net/nl will link to the English donation page (same for German).
So we're never drawing a blank, but there's room for improvement.

**Comment by thomasd8** [comment]
> So we're never drawing a blank, but there's room for improvement to ensure that the donation page is shown in the correct locale.

I've filed this as #256 - Donate links from localized Thunderbird homepages all end up on en-US donation page instead of existing localized donation pages

**Comment by Pomax** [comment]
>That's misspelt.

correct, I hand typed it.

> Not true. They may end up on the English donation page, but not with 503.

Some where 503, possibly related, possibly not. Some are indeed 302's.
