### ISSUE TITLE
`Donate` links from localized Thunderbird homepages all end up on en-US donation page instead of existing localized donation pages

### ISSUE THREAD

**Issue by thomasd8** [thundernest/thunderbird-website#256]
STR

1. Go to https://www.thunderbird.net/nl   (or any other language which may have full localization)
2. Follow [Donate] button link in upper right corner

Actual result
- https://donate.mozilla.org/thunderbird/?utm_source=thunderbird.net&utm_medium=referral&utm_content=header
- redirects to: https://give.thunderbird.net/en-US/?utm_source=thunderbird.net&utm_medium=referral&utm_content=header
- iow, donation page is shown in en-US instead of localized version

Expected result
- show existing localized version of donation page:
- https://give.thunderbird.net/nl/

Someone with the required knowledge should fix this - we have localized donate pages for a reason, not to bypass them...

**Comment by thomasd8** [comment]
Coming from #254 and #255 which will change the link to use give.thunderbird.net directly - is that enough to make the localized links work again?

**Comment by Sancus** [comment]
The change to give.thunderbird.net is live already and I'm seeing it on the front page in most languages, some may have the old version cached still however. That should clear up within an hour or two.

We do not and never have linked directly by language code, because our language list and the donate site's are not necessarily the same. We link to https://give.thunderbird.net with no locale code and let it decide what language is correct based on the user's Accept-Language again.
