### ISSUE TITLE
get-involved cites MDN for localization reference

### ISSUE THREAD

**Issue by wsmwk** [thundernest/thunderbird-website#263]
"For localization of Thunderbird itself, see Thunderbird Localization on MDN. " is incorrect on https://www.thunderbird.net/en-US/get-involved/

**Comment by Sancus** [comment]
Where should it link to instead? or do you want me to remove it?

**Comment by wsmwk** [comment]
I don't think it should be removed. But someone else will need to provide the correct info.  @jfx2006 ?

**Comment by Sancus** [comment]
here are the old docs: http://web.archive.org/web/20190220021446/https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Thunderbird/Thunderbird_Localization#Getting_l10n-relevant_information

How much of this is still correct? Should it be rehosted on developer.thunderbird.net maybe or something like that?

**Comment by jfx2006** [comment]
Some of that is relevant, some is not. In any case, if MDN isn't hosting it, we can put it on DTN.

> I don't think it should be removed. But someone else will need to provide the correct info. @jfx2006 ?

**Comment by hamishwillee** [comment]
Probably no one will be linking to the MDN doc anymore, but we can provide a redirect from the archived page (if you want one) when you have an alternative target

**Comment by jikamens** [comment]
Ping. There's still nothing online that I could find documenting how to translate Thunderbird. It took me over an hour yesterday to figure out where the translations are stored. Wish I'd found this bug at the start of that rather than the end. I'd submit a PR if it weren't for the fact that I don't think I'm enmeshed enough in all this stuff to get it right; I think it needs to be done by someone with more familiarity about how everything hangs together.

**Comment by Sancus** [comment]
I updated that link to the point to the source docs, which is the best we have for this for now. They should get more details at some point. But they at least link to Pontoon which is the important part.
