### ISSUE TITLE
Can we Incorporate Bootstrap into Start Page?

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#29]
Currently I'm working on updating the start page, but it seems as though we don't have as much control over how content appears as I'd like. I was looking at how the CSS is compiled from less. I was curious as to how hard it would be to implement bootstrap into the website, and how this would properly be done? If it is as trivial as just dropping the css file in as a dependency that's great. Please advise.

**Comment by ryanleesipes** [comment]
Just FYI, Bootstrap is found here: https://getbootstrap.com/

**Comment by Sancus** [comment]
The start page loads every time someone starts the Thunderbird client. It needs to be as minimalist and quick-loading as possible. In fact I've been meaning to go back to it at some point and fix it so that it's just one http request by in-lining all the CSS and images into the page the way it used to be before they messed it up on the import to mozilla.org

Bootstrap is 141KB of minimized CSS. The whole start page right now is about ~200KB, so that's a 70% increase to the size of the page.  This isn't significant for people on broadband, but for people who don't(still plenty of those out there) it's significant. It's also very significant in terms of our Cloudflare bandwidth usage, which is free atm.

So if you just want the bootstrap CSS maybe, if you want the JS part then I really would argue against that because that will impact performance even after the page is cached.

The question is more, can we just do whatever layout you want without Bootstrap's overhead? The answer is most likely yes, and for the start page in particular it is best to avoid framework and library bloat.

**Comment by ryanleesipes** [comment]
It's a good question @Sancus - whether the layout I want can be accomplished without Bootstrap or some other library's added bulk. I'm still experimenting with what we have on the start page, as you can see in #30. 

Is there any documentation for the website that I'm not aware of? It's pretty straightforward, but I'm not sure why the "<section>" layout places things from right to left. Meaning when they are condensed for a smaller screen it appears in the opposite order (the things on the right appear on top of the things on the left). It's stuff like this that makes me wish I was using bootstrap.

**Comment by ryanleesipes** [comment]
Closing this, I'm up to speed.
