### ISSUE TITLE
Automate Calendar Generation

### ISSUE THREAD

**Issue by Sancus** [thundernest/thunderbird-website#298]
We currently crowdsource calendar .ics files. This is error prone, and wastes time both ensuring correctness and reviewing update requests.

Considering there are now relatively high quality data sources like https://github.com/dr-prodigy/python-holidays or possibly https://calendarific.com/ there seems to be no good reason to continue with the manual, crowdsourced calendars.

**Comment by tobiscode** [comment]
Hi,

I've looked into this and this seemed not too complicated so I wanted to offer my help.

I've forked the repository and created a Python script based on the [holidays](https://github.com/dr-prodigy/python-holidays), [icalendar](https://github.com/collective/icalendar), and [pycountry](https://github.com/flyingcircusio/pycountry) packages to generate calendars for all countries and subdivisions supported. I've created a [branch](https://github.com/tobiscode/thunderbird-website/tree/holiday-calendar-autogen) with the changes, including the newly created `.ics` files. The script also updates the `calendars.json` file, assuming that that's what the website builder checks to create links. I've tested the output calendar files locally and they seem to work.

A couple of things I want to note:

1. Currently, the script creates calendar files for all possible country subdivisions, but does not add them to the `calendars.json` file, since I'm not sure what the best format for that would be - happy to add it if there's a format I can follow.
2. The calendar files only create a minimum amount of holiday event metadata: only the name and date. I could add fields like a `LAST-MODIFIED` or `UID`, although I'm not sure whether that would actually help in any way and just complicate things.
3. The `PRODID` calendar value should probably be changed to something more meaningful
4. Maybe the `ALL_YEARS` list in the generator script could be changed to something that is relative to the current date.
5. The [holidays](https://github.com/dr-prodigy/python-holidays) package contains, as far as I can tell, only the official holidays. Looking at the US holidays, events like Election Day (which is wrong for 2022, see https://github.com/thundernest/thunderbird-website/issues/297) are _not_ included. This could confuse users who have subscribed to the current versions of calendars.
6. Before generating the new set of calendar files, I've deleted the old ones without checking if all old ones are included in the new ones. I think that out of consistency, this would be the right thing to do. Since all calendar files are public in this git repository, they could still add the old calendars using a permalink to the latest commit before the change to the automatic script, e.g. [USHolidays.ics](https://github.com/thundernest/thunderbird-website/blob/3dd1ab1aa25caf2846ac7202468cb615dbf14eb4/media/caldata/USHolidays.ics).
7. I'm not sure whether the root directory is the right place to put the `generate-holiday-ics.py` file.
8. Regarding the selection of the packages, I did not do research whether these were the best/most appropriate upstream packages to use. I preferred the `holidays` package over _Calendarific_ just because it is open source, and I used `icalendar` just because it is already a dependency of the website repository.
9. Since I coded this up real quick on my Windows machine, I didn't check how the `CRLF` line endings in all the written files propagate to Linux machines through git, and I didn't check if that could present a problem to Thunderbird imports.

I hope this can be useful to Thunderbird users. I've never contributed to a public repository through a fork so please let me know if my solution is useful and could be merged. I'm happy to make modifications to my branch as needed. Please let me know how to proceed.

Cheers
