### ISSUE TITLE
Use download bouncer URLs for Thunderbird Daily download button

### ISSUE THREAD

**Issue by jfx2006** [thundernest/thunderbird-website#327]
After bugs 1781072 and 1785143 are completed, the download bouncer will support the "thunderbird-nightly-latest" family of products, always redirecting to the latest Thunderbird Daily build.

The download button for Thunderbird Daily can use URLs like https://download.mozilla.org/?product=thunderbird-nightly-latest-SSL&os=linux64&lang=en-US instead of the current links to the FTP archive.

**Comment by Sancus** [comment]
I guess this is fine since daily version numbers don't change during their cycle anyways so they don't mean much. This will require change here: https://github.com/thundernest/thunderbird-website/blob/master/product_details.py#L121 and `DAILY_URL` can then be removed from `settings.py`.

The version number will still be used to pull the relevant data from product details(mainly language and OS availability).
