### ISSUE TITLE
Documentation, What we need and where it should live.

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#35]
This is more of a meta bug for the website. As it relates to Thunderbird's web presence, but does not necessarily mean what we detail here will live on the website.

As per #28 - it appears as though we need to determine, more in-depth, what documentation is useful to contributors and where it should live. Right now we have the Wiki as well as MDN. I'd like to propose we have a discussion as to what it missing or hard to find currently, as well as the state of our existing documentation. And whether it should all remain where it is or be migrated.

Also related is @jerrac's Discourse post on Communication and Documentation: https://discourse.mozilla.org/t/consolidating-documentation-and-communication/27849/2

Putting this here so we can implement #28, and then carry on with the ancillary work detailed above.

**Comment by Sancus** [comment]
Well I guess it depends on what documentation you mean. For the github repos I am responsible for, I firmly believe that the documentation should be with the code. Mozilla tends to use Sphinx to produce documentation that gets hosted on readthedocs. Like the [docs for mozilla.org](http://bedrock.readthedocs.io/en/latest/).

Having a separate wiki makes it even less likely documentation will be maintained. There's a reason I've kept to a README for each repository on here, and that's because for documentation to be useful someone(ie: me) has to keep it updated. That's already been pretty difficult, and right now documentation is a single page that anyone can pull request to. We could move up to using Sphinx -- but I really don't think it's needed for now.

Increasing the complexity of our document hosting by adding a wiki or domain doesn't seem particularly useful. Documentation on Thunderbird itself is a different story, it's extremely complex, and it's also inextricably intertwined with Gecko and Firefox documentation, which is why having it on MDN makes sense. If you want to move Thunderbird documentation off MDN that's a conversation that should happen elsewhere.

**Comment by ryanleesipes** [comment]
Agreed, on all points. The reason I created this issue and he question I have, that has arisen from #28  is: How much "documentation" should live on the website? This is something that I'd like to discuss so that we have a clear idea of what the scope of the website is. For instance, can tutorials live on the website? The answer is probably "no", but we should discuss it so that we have a clear delineation of what should be on thunderbird.net and what should not.

**Comment by jerrac** [comment]
If we're talking about this repository, I wouldn't expect anything beyond pointer pages like /get-involved to be here.

If we're talking about documentation that lives under the thunderbird.net domain, then I'd say there's more to talk about.

**Comment by Sancus** [comment]
I think it's reasonable to set up a wiki on the thunderbird.net domain at some point. Since we're already committed to a database server for the addons site, we can just use that. Cost should be <$100/mo... I'd probably put it on its own ec2 instance.

I'm not opposed to adding more documentation on the website, but it is obviously more difficult to update that way, and the tools for review and editing are a lot more cumbersome and time consuming.

We could consider removing Thunderbird participation from wiki.mozilla.org and putting it on wiki.thunderbird.net or something. I just want to be sure we're actually consolidating/usefully improving documentation and not just adding yet-another-place-to-look. So we should probably be removing at least one "place to look" if we are adding an additional one.

**Comment by wsmwk** [comment]
> P.S. This might be better suited as a maildev conversation. Or discourse.

Note, maildev was created for code issues - especially futures.  tb-planning with ~270 subscribers remains the defacto location for open discussion of non-code issues.

**Comment by Sancus** [comment]
Yeah that's fair, so tb-planning instead of maildev.

**Comment by ryanleesipes** [comment]
Copy that. Will move over to tb-planning.
