### ISSUE TITLE
Mistake in the German localization of the "What's new"-page for version 115.3.1

### ISSUE THREAD

**Issue by Matthias-Hammel** [thundernest/thunderbird-website#511]
At about the middle of the page https://www.thunderbird.net/de/thunderbird/115.0/whatsnew/?locale=de&version=115.3.1&channel=release&oldversion=102.15.1 below the headline "Neue + sortierbare Ordnermodi" is the text "oder verschiedenen Sie Ihre Bereiche für die bevorzugten Ordnermodi". This should be "oder verschieben Sie Ihre Bereiche für die bevorzugten Ordnermodi". The current sentence makes no sense. "verschiedenen" is the plural of "verschieden" ("different") while "verschieben" means "move".

**Comment by Sancus** [comment]
Hi,

Translations are done on Pontoon by the community, so if you can please submit the correction there so that it gets approved by the German localization manager, that would be ideal.

The string you're talking about is here I think:

https://pontoon.mozilla.org/de/thunderbirdnet/LC_MESSAGES/messages.po/?search=sortable&string=281643

**Comment by Matthias-Hammel** [comment]
Hi,
thanks for info, I've submitted the correction there and close this issue.
