### ISSUE TITLE
Create About page explaining who owns/manages Thunderbird, and relationship to Mozilla

### ISSUE THREAD

**Issue by chrisilias** [thundernest/thunderbird-website#55]
We sometimes come across both users and contributors who say something like "_I thought Thunderbird was dead_" or in [my latest experience](https://support.mozilla.org/en-US/forums/knowledge-base-articles/712230?page=2#post-74335) "_is Mozilla planning on keeping Thunderbird? I remember a while ago they were looking to dump Thunderbird and give it to some other open source organization_"

I looked for a page that explains who owns Thunderbird, what the council is, and what the relationship between Thunderbird and Mozilla is, but I couldn't find anything. The closest was [this blog post](https://blog.mozilla.org/thunderbird/2017/05/thunderbirds-future-home/).

I was thinking of creating a support article for it, but I think it would be more appropriate on thunderbird.net.

**Comment by wsmwk** [comment]
On 8/2/2018 7:37 PM, chrisilias wrote:
>
> We sometimes come across both users and contributors who say something 
> like "/I thought Thunderbird was dead/" or in my latest experience 
> <https://support.mozilla.org/en-US/forums/knowledge-base-articles/712230?page=2#post-74335> 
> "/is Mozilla planning on keeping Thunderbird? I remember a while ago 
> they were looking to dump Thunderbird and give it to some other open 
> source organization/"
>
> I looked for a page that explains who owns Thunderbird, what the 
> council is, and what the relationship between Thunderbird and Mozilla 
> is, but I couldn't find anything. The closest was this blog post 
> <https://blog.mozilla.org/thunderbird/2017/05/thunderbirds-future-home/>.
>
> I was thinking of creating a support article for it, but I think it 
> would be more appropriate on thunderbird.net.
>
Perhaps it could be done in a broader context, in a short history of 
Thunderbird.

**Comment by kewisch** [comment]
We'd have to keep the history short though to avoid tldr. I would very much enjoy having a page that introduces the council, along with a quick mission statement, and said short history.

**Comment by ryanleesipes** [comment]
Sounds like an About page is in order.

**Comment by markrousell** [comment]
I was going to create a new issue on this subject but I see that we have this one already. I'll just add some further thoughts.

(1) Yes, a 'Governance' section is definitely needed on thunderbird.net. This issue was discussed recently here: https://groups.google.com/d/msg/mozilla.general/rR_3o-tM1uY/aG3OAC6eAgAJ (I see that Wayne has commented above here too).

(2) There is no roadmap or strategy document for Thunderbird on thunderbird.net. As per my comments in http://lists.thunderbird.net/pipermail/maildev_lists.thunderbird.net/2018-August/001262.html it seems to me that the lack of on the website of (a) as above, a governance section (detailing the Council and the ESC, if and when it is properly formed) and (b) **a detailed and agreed roadmap for Thunderbird** are harming people's perceptions of Thunderbird.

The lack of both these sections/documents is feeding into the "I thought Thunderbird was dead" meme.

I realise that getting a roadmap/strategy document (both a public version and a much more detailed version for developers to follow) is an issue that is outside of the scope of website design and content, but some kind of TB roadmap is surely needed even if it's a pro tem entry until the Council, ESC, or someone can produce such a roadmap.

**Comment by jotasprout** [comment]
Can I take this on? I've been wanting to get started with contributing to Mozilla forever. Tried very hard to get my foot in with Sea-Monkey but never happened. _**I'd love to do this.**_

**Comment by mkmelin** [comment]
@jotasprout great! Please go ahead.
@markrousell I think a roadmap probably doesn't belong on that page, but elsewhere on more developer targetting pages. It also wouldn't be localized etc.

**Comment by jotasprout** [comment]
Woo-hoo! I am _on the case!_

**Comment by jotasprout** [comment]
Should a link to this go under the Thunderbird menu in the top nav? Would changing the name of that menu to "About" be better and call this new page "Who We Are"?

**Comment by Sancus** [comment]
Usually this kind of page is called something like "About Us", and yeah I think it should go under the Thunderbird menu. I don't think that the name of that menu should be changed, it links to some very important pages and hovering a menu named "About" to see the Features or Beta pages doesn't make much sense.

**Comment by jotasprout** [comment]
On the website, the Thunderbird menu contains "Features", "Beta", and "Releases" among other items. In the repo, however, features is a sibling folder to thunderbird. Should this About page be "website/thunderbird/about/index.html" or "website/about/index.html"?

**Comment by Sancus** [comment]
`website/about/index.html` - the `/thunderbird/` dir is for stuff related to thunderbird application versions and downloading them specifically.

**Comment by ryanleesipes** [comment]
@jotasprout are you still looking at this? We should sync up on what content you need from us!

**Comment by markrousell** [comment]
> @markrousell I think a roadmap probably doesn't belong on that page, but elsewhere on more developer targetting pages. It also wouldn't be localized etc.

(Apologies for the delay in replying!)

Exactly where a roadmap should go is an important question but a roadmap is definitely important not just for devs or wouldbe devs but for end users themselves and, critically, for influencers.

People (both end users and those who influence them or who choose software for end users to actually use) badly need to know that a project is alive, healthy, and has a clearly defined future that people are working towards. Ways to do this include a clearly-visible roadmap, together with achievements ticked off (or otherwise clearly visible) as they are reached.

A roadmap is a marketing tool for the general public (and businesses). It's not just something of interest to developers.

**Comment by ryanleesipes** [comment]
#94 is a good first step to this. Could use some more work though.

**Comment by Sancus** [comment]
https://www-stage.thunderbird.net/en-US/about/ 

This is now on stage, last chance for any critical feedback. Will go live tomorrow.

**Comment by wsmwk** [comment]
Third sentence under TB and foundation seems awkward, in part because it is unclear whether the part after the dash refers to MoFo or MoCo.  Unclear how best to improve it - maybe something like "The Foundation is also the sole shareholder in the Mozilla Corporation; the Foundation's focus is on advocacy issues and keeping the Internet healthy, whereas the Corporation's focus is on developing and delivering Firefox."?

> The Foundation is also the sole shareholder in the Mozilla Corporation, the maker of Firefox - but has its focus on advocacy issues and keeping the Internet healthy.

**Comment by Sancus** [comment]
> Third sentence under TB and foundation seems awkward, in part because it is unclear whether the part after the dash refers to MoFo or MoCo.

This didn't really bother me, but, I think you can increase clarity here just by moving the order around -> 

> The Foundation is focused on advocacy issues and keeping the Internet healthy, but is also the sole shareholder in the maker of Firefox, the Mozilla Corporation.

**Comment by wsmwk** [comment]
@Sancus great suggestion.

**Comment by Sancus** [comment]
I edited that Mozilla Foundation paragraph to make it flow better and not repeat "The (Mozilla) Foundation" so many times.

I also pulled URLs out of the strings so we can change them without blowing up l10n, added a wiki URL function and removed newlines from the strings because gettext picks them up.

I also added a Trello task to myself to document all the quirks of adding pages to the website in more detail. Even I forget things sometimes.

The page is submitted for localization, I will probably leave it on stage only for a week or so to give localizers some time to do their thing before it goes live.
