### ISSUE TITLE
Dead links in the "Holiday Calendars" page

### ISSUE THREAD

**Issue by plule** [thundernest/thunderbird-website#57]
Hello, in the [Holiday Calendars](https://www.thunderbird.net/en-US/calendar/holidays/) page, all the "letter" links are dead.

For instance "A" redirects to [https://www.thunderbird.net/en-US/calendar/holidays/A](https://www.thunderbird.net/en-US/calendar/holidays/A), which is a 404.

**Comment by wsmwk** [comment]
@Sancus these index links are missing "#" in front of the letter

**Comment by Sancus** [comment]
Super weird, cause I copy pasted that file from bedrock. Not sure how that got messed up. Anyway, this is fixed on stage: https://www-stage.thunderbird.net/en-US/calendar/holidays/ in https://github.com/thundernest/thunderbird-website/commit/578f27743f5a54fbfb510ac6940847872efecabf

I don't want to push the whole master branch live, since we are still missing Italian and Spanish for major translations of the new start page, and this is minor enough that I don't think it's worth cherry picking, so it will wait until the start page update, which should hopefully be ready in no more than a week.

Leaving this open until fix is live.

**Comment by Sancus** [comment]
This is fixed.
