### ISSUE TITLE
"No beta is currently available" on the Beta page

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#58]
There should be no download available on the beta page as it has 60.0beta10 which is older than the release page 60.0.
https://www.thunderbird.net/channel/

Perhaps the beta page could instead state:
"No beta is currently available"
Note: this was reworded from https://www.libreoffice.org/download/pre-releases/ which states:
"No RC is currently available for the 6.0 codeline"

What do you think?

**Comment by wsmwk** [comment]
On 8/6/2018 9:30 AM, ovari wrote:
>
> There should be no download available on the beta page as it has 
> 60.0beta10 which is older than the release page 60.0.
> https://www.thunderbird.net/channel/
>
> Perhaps the beta page could instead state:
> "No beta is currently available"
> Note: this was reworded from 
> https://www.libreoffice.org/download/pre-releases/ which states:
> "No RC is currently available for the 6.0 codeline"
>
> What do you think?
>
Thanks, but no, we're not going to make that change - because beta and 
release channel are two separate entities. People chose beta for a 
reason, and changes/updates in release channel don't impact what people 
want from beta.

When a newer beta becomes available the page will automatically update

**Comment by Sancus** [comment]
Yeah I don't think this is a good idea. There is only a brief period once per year where the beta is "out of date", if ever, and it's not a big deal when it is, because it usually includes most if not all of the changes of the slightly newer ESR version. I think it's better for people to always be able to get a beta version, so that they are on the update channel they want to be.

Plus this would require some special effort and code to make it possible to blank the beta page like this on demand, which is added complexity for minimal benefit.

Thanks for the suggestion, though.
