### ISSUE TITLE
thunderbird.net/thunderbird/system-requirements/ falls back to old Thunderbird version

### ISSUE THREAD

**Issue by chrisilias** [thundernest/thunderbird-website#66]
In support pages, we'd like to provide version/locale neutral links to the system requirements, but the URL https://www.thunderbird.net/thunderbird/system-requirements/ falls back to requirements for 52.6.0, not the latest version.

**Comment by Sancus** [comment]
This was lost in the move to thunderbird.net because the new site is just static files, and doesn't really support dynamic redirects.

I've added some .htaccess files in the build script to bring these back, they'll be updated on each build and that should be sufficient.

Fixed by https://github.com/thundernest/thunderbird-website/commit/8bb21b4dbdcc9bd9e48b3b7b31d82896cefca7bf and live.
