### ISSUE TITLE
Download Redirects in Edge open a tab instead of redirecting

### ISSUE THREAD

**Issue by MadMattAu** [thundernest/thunderbird-website#70]
I just did a little testing of the download process in Edge, chrome and Firefox.  While the page redirect to the donate worked well in Chrome and Firefox, however the redirrect opened a new tab in Edge.

This is a problem as unless the user noticed the blinking tab on the original download page, they assume they must donate or something before they actually get a download.  Can the redirect be changed in some way to make it not open a new tab in Edge and behave as it does in chrome and Firefox?

**Comment by Sancus** [comment]
Unfortunately Edge's behaviour with redirects is strange, it actually cancels the download prompt entirely when the redirect triggers. So we can't use redirects because that will prevent you from downloading at all.

I deliberately changed Edge to a new tab because of this behaviour. The donate page is supposed to have a banner at the top linking you to a direct download page anyway if for some reason you don't see the tab, but it seems like Mozilla broke it with a new a-b-c test they're running, I've [filed an issue for that](https://github.com/mozilla/donate.mozilla.org/issues/2071).

I can't think of a better way to do this for Edge, but I would accept a patch. Edge is <10% of visitors to this site and I already spend a long time fiddling with this logic, so I don't think it's worth committing any additional time to this.

**Comment by ryanleesipes** [comment]
Perhaps we can prevent Edge from doing anything at all besides starting the download. Donations are up a considerable amount, but there are quite a few confused non-technical users. What do you think @Sancus - can we change the behavior based on browser?
