### ISSUE TITLE
Add MSI package to Organizations page

### ISSUE THREAD

**Issue by ovari** [thundernest/thunderbird-website#85]
Please provide a link a Windows MSI package on [Download Thunderbird in your language](https://www.thunderbird.net/thunderbird/all/) page as [Provide Thunderbird MSI package](https://bugzilla.mozilla.org/show_bug.cgi?id=274624) has been resolved as fixed.

Thank you

**Comment by mkmelin** [comment]
Eventually yes, but it's only for Daily so far, and there are yet issues to sort out.

**Comment by Sancus** [comment]
Are these intended to replace the executable? If so, download.mozilla.org should just return them instead of the executable and no change to the website would be necessary.

I hope that they are intended to replace the executable because offering two Windows download options just seems needlessly confusing and bad for users.

**Comment by ovari** [comment]
> Let's follow what Firefox does, but they haven't started promoting the MSIs in any way yet, AFAIK.

[Firefox customization with MSI installers](https://support.mozilla.org/en-US/kb/firefox-customization-msi-installers)

[Mozilla to Provide MSI Installers Starting with Firefox 65](https://www.bleepingcomputer.com/news/software/mozilla-to-provide-msi-installers-starting-with-firefox-65/)

**Comment by mkmelin** [comment]
I doubt we'd package more than a single version. That sounds like a huge waste of bandwidth.
Anyway, the next major release is tb 68, so this is a bit down the road still.

**Comment by Sancus** [comment]
Ah, if this is intended specifically for enterprise installers, there's no reason to offer it to regular users, we could have a separate download page for these or just keep them on FTP only and link to them from a page explaining them. Agreed we should wait and see how Firefox handles this.

This can sit until we have an actual plan for these files.

**Comment by Sancus** [comment]
The plan is to mention this installer on the [org page](https://www.thunderbird.net/en-US/organizations/). This is [also what Mozilla does w/Firefox](https://www.mozilla.org/en-US/firefox/enterprise/).

**Comment by mkmelin** [comment]
Maybe we should have a link from the "all" downloads page to the org page too. Maybe under the "Release notes" link.

**Comment by wsmwk** [comment]
Mention of msi on https://www.thunderbird.net/en-US/thunderbird/all/ is a good idea, but rather than a DL link I thtink it should go to  https://www.thunderbird.net/en-US/organizations/ ... and the download link only offered from the organiations page. 

It also looks like https://www.thunderbird.net/en-US/organizations/ is sparse, and needs improvement

**Comment by Sancus** [comment]
I've added Win64 MSI to Systems & Languages page. 32-bit doesn't seem to be built atm, not sure if we are planning to build it or if anyone cares about 32-bit. I assume not.

The MSI link uses the win32 icon and I'm not fixing that because icons are going away in a few weeks with the redesign anyways.
