### ISSUE TITLE
Have you guys considered switching over to SCSS?

### ISSUE THREAD

**Issue by jcklpe** [thundernest/thunderbird-website#87]
It appears that ya'll are using less? Have ya'll considered using SCSS? Less has had year on year decreasing use and SCSS is basically the standard now. Also SCSS gracefully takes native CSS no problem while SASS and LESS do not. 

I'm a UX Designer and Dev and I wanted to get involved in the new thunderbird UI redesign. I tried going through topicbox but it 1) seems pretty dead and 2) is broken and won't let me join the UX group. Already sent ya'll's community manager some info on it. 

I'd like to get involved as much as I can.

**Comment by jcklpe** [comment]
Also I know it's not open source but do you guys have any kind of slack or discourse? Or maybe even a rocketchat? traditional non-cloud IRC kind of sucks for discussion as it doesn't log any comments while you're away so it's hard to stay in the loop.

**Comment by Sancus** [comment]
There's no reason to put work into switching from LESS to SCSS when the website gets minimal design changes from month to month. It works as-is.

If we do a full redesign or someone wants to work on a redesign sure, they could use SCSS. The only important part is that all pages that we have now need to have a replacement that looks or correct or need to still work and look correct. I'm aware there are various converters so that shouldn't be too hard.

We don't have slack/discord/rocketchat, and there are no current plans to use them -- it's likely that quite a few of the people who work on Thunderbird would be against using these proprietary solutions on privacy, security, and lack of control(It's not fun when your [users get banned just because Slack felt like it](https://www.theverge.com/2018/12/20/18150129/slack-iran-deactivated-sanctions-license-cuba-crimea)) grounds. 

If you want a chat history with IRC try [a bouncer](https://wiki.znc.in/ZNC) or [IRC Cloud](https://www.irccloud.com/). I use ZNC myself.

Finally, most of these comments aren't a website issue or relevant to the website, if you are looking for ways to communicate with the project [these are extensively documented](https://www.thunderbird.net/en-US/get-involved/#communication). Most developer discussion occurs on IRC, mailing lists, and a bit on Bugzilla.

**Comment by jcklpe** [comment]
@Sancus RocketChat is not proprietary. It's open source. https://rocket.chat/ My wording on that was a little confusing though. 

Hadn't heard of IRC Cloud though. Neato.

**Comment by kewisch** [comment]
Topicbox is what we are currently testing since we have it included in another tool, I'm sure Ryan will get back to you soon when he is back from PTO. Our community is fairly small, so really anything we have may first seem like it is not the most up to date channel. I'd suggest to post something on topicbox once you have access.

Looking forward to seeing your contributions!

**Comment by Sancus** [comment]
> @Sancus RocketChat is not proprietary.

Ah you're right, I just hadn't heard of it and assumed it was another slack clone or something. Good to know that exists.
