### ISSUE TITLE
404 Page not Working

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderbird-website#91]
We have a 404 page, but it's not redirecting to it. @Sancus what needs to be put in place to make that happen?

**Comment by clokep** [comment]
404.html (which exists) just needs to be found on the template search path: https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/#customize-the-default-error-views

**Comment by Sancus** [comment]
The website isn't Django, so that's not super useful. This is a known bug, because I couldn't figure out how to instruct Apache to find the localized 404 pages. Nginx has a super simple method in config file due to its locations system, but Apache does not.

I had messed around with regex rewrites for a while trying to figure it out but couldn't get anything to actually work.

However, I think I just found a simple solution, putting a .htaccess in each of the language roots pointing at the correct file seems to do the trick and is easy to generate during site build since we already generate .htaccess files for some other things.

Should have a patch tomorrow.

**Comment by Sancus** [comment]
Fixed in https://github.com/thundernest/thunderbird-website/commit/00bbba5cf45d89a83ff43159f7cfe10034a50414 and live now.

**Comment by clokep** [comment]
Oops, I got this confused with the add-ons site. My bad! 👎

**Comment by ryanleesipes** [comment]
There is still a bug. It appears as though it will not find the 404 page if the locale isn't set.
For instance, visiting https://thunderbird.net/contact-we doesn't show the 404 page.
Visiting https://thunderbird.net/en-US/contact-we does.

**Comment by Sancus** [comment]
I set this to the en-US page yesterday, that's good enough for now. In theory arbitrary URLs should redirect to the language code and THEN 404, but that is a harder problem to solve, I added it as a task trello-side for sometime later, it would be useful for other reasons as well.
